# Generated by Django 4.2.1 on 2023-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
