# Generated by Django 4.2.1 on 2023-06-22 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ManyToManyField(blank=True, related_name='freelancer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
