# Generated by Django 4.2.1 on 2023-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment',
            field=models.IntegerField(null=True),
        ),
    ]
