# Generated by Django 4.2.1 on 2023-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
