# Generated by Django 4.2.1 on 2023-06-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='freelancer',
            field=models.ManyToManyField(related_name='freelancer_favorite_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='freelancer',
            field=models.ManyToManyField(related_name='freelancer_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
