# Generated by Django 4.2.1 on 2023-06-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
