# Generated by Django 4.2.1 on 2023-06-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_comment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
